[build]
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" # Força o uso do esbuild para empacotar as funções
  external_node_modules = ["nodemailer"] # Garante que o nodemailer seja incluído

[build.command]
  command = "bun run build"

